// Copyright (C) 2026 Tencent. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// TSIfDef postinstall：在宿主工程的 node_modules 里生成一个转发包
// eslint-plugin-tsifdef，重新导出 tsifdef/eslint-plugin。
//
// 为什么需要它：ESLint（eslintrc 格式）把 `plugins: ["tsifdef"]` 解析成
// 包名 `eslint-plugin-tsifdef`，无法直接指向 `tsifdef` 包。npm alias 会拿到
// 主入口（core），没有 processors。所以由本脚本在安装时自动铺一个极小的转发包，
// 让工程零手写即可 `plugins:["tsifdef"] + processor:"tsifdef/macros"`。
//
// 安装时 npm 以本包目录（node_modules/tsifdef）为 cwd 运行本脚本；转发包建在
// 同级 node_modules/eslint-plugin-tsifdef。幂等；任何失败都不阻断安装。
"use strict";

const fs = require("node:fs");
const path = require("node:path");

try {
  // 本脚本位于 <install>/node_modules/tsifdef/scripts/postinstall.cjs
  // 目标转发包位于 <install>/node_modules/eslint-plugin-tsifdef
  const tsifdefPkgDir = path.resolve(__dirname, "..");
  const nodeModulesDir = path.resolve(tsifdefPkgDir, "..");

  // 仅当确实处于某个 node_modules 下（真实安装场景）才铺设，
  // 避免在 tsifdef 仓库自身开发时误建。
  if (path.basename(nodeModulesDir) !== "node_modules") {
    process.exit(0);
  }

  const shimDir = path.join(nodeModulesDir, "eslint-plugin-tsifdef");
  fs.mkdirSync(shimDir, { recursive: true });

  fs.writeFileSync(
    path.join(shimDir, "package.json"),
    JSON.stringify(
      {
        name: "eslint-plugin-tsifdef",
        version: "1.0.0",
        private: true,
        main: "index.js",
        description: "Auto-generated forwarder to tsifdef/eslint-plugin (do not edit).",
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );

  fs.writeFileSync(
    path.join(shimDir, "index.js"),
    "// Auto-generated by tsifdef postinstall. Forwards to tsifdef/eslint-plugin.\n" +
      "module.exports = require('tsifdef/eslint-plugin');\n",
    "utf8",
  );
} catch {
  // 转发包生成失败不应让 npm install 失败；工程仍可手动铺设。
}

process.exit(0);
