// Copyright (C) 2026 Tencent. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// TSIfDef postinstall: create an eslint-plugin-tsifdef forwarding package in
// the host project's node_modules that re-exports tsifdef/eslint-plugin.
//
// Why this is needed: ESLint's eslintrc format resolves `plugins: ["tsifdef"]`
// to the package name `eslint-plugin-tsifdef` and cannot point directly at the
// `tsifdef` package. An npm alias resolves to the main core entry, which has no
// processors. This script installs a tiny forwarder so projects can use
// `plugins:["tsifdef"] + processor:"tsifdef/macros"` without a manual shim.
//
// npm runs this script from node_modules/tsifdef during installation. The
// forwarder is created in the sibling node_modules/eslint-plugin-tsifdef.
// The operation is idempotent, and failures never block installation.
"use strict";

const fs = require("node:fs");
const path = require("node:path");

try {
  // This script lives at <install>/node_modules/tsifdef/scripts/postinstall.cjs.
  // The forwarder lives at <install>/node_modules/eslint-plugin-tsifdef.
  const tsifdefPkgDir = path.resolve(__dirname, "..");
  const nodeModulesDir = path.resolve(tsifdefPkgDir, "..");
  const tsifdefVersion = JSON.parse(
    fs.readFileSync(path.join(tsifdefPkgDir, "package.json"), "utf8"),
  ).version;

  // Install only when actually running below node_modules, avoiding accidental
  // creation while developing in the tsifdef repository itself.
  if (path.basename(nodeModulesDir) !== "node_modules") {
    process.exit(0);
  }

  const shimDir = path.join(nodeModulesDir, "eslint-plugin-tsifdef");
  fs.mkdirSync(shimDir, { recursive: true });

  fs.writeFileSync(
    path.join(shimDir, "package.json"),
    JSON.stringify(
      {
        name: "eslint-plugin-tsifdef",
        version: tsifdefVersion,
        private: true,
        main: "index.js",
        description: "Auto-generated forwarder to tsifdef/eslint-plugin (do not edit).",
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );

  fs.writeFileSync(
    path.join(shimDir, "index.js"),
    "// Auto-generated by tsifdef postinstall. Forwards to tsifdef/eslint-plugin.\n" +
      "module.exports = require('tsifdef/eslint-plugin');\n",
    "utf8",
  );
} catch {
  // A forwarder failure must not fail npm install; projects can add it manually.
}

process.exit(0);
