// Copyright (C) 2026 Tencent. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

const { readFileSync, writeFileSync } = require("node:fs");
const { join, resolve } = require("node:path");

const root = resolve(__dirname, "..");
const versionPath = join(root, "src", "version.ts");
const packagePath = join(root, "package.json");
const lockPath = join(root, "package-lock.json");
const tsserverPackagePath = join(root, "scripts", "packaging", "tsserver", "package.json");
const readmePaths = [join(root, "README.md"), join(root, "README.zh-CN.md")];

function parseJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function writeJson(path, value) {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

/**
 * Update the version in each README's title and changelog badge. These were
 * maintained by hand and silently fell behind package.json.
 */
function syncReadme(path, version) {
  if (!require("node:fs").existsSync(path)) {
    return;
  }
  const before = readFileSync(path, "utf8");
  const after = before
    .replace(/^# TSIfDef \d+\.\d+\.\d+$/m, `# TSIfDef ${version}`)
    .replace(/(badge\/changelog-)\d+\.\d+\.\d+(-orange)/g, `$1${version}$2`);
  if (after !== before) {
    writeFileSync(path, after, "utf8");
  }
}

function main() {
  const packageJson = parseJson(packagePath);
  const version = packageJson.version;
  if (typeof version !== "string" || version.trim() === "") {
    throw new Error(`package.json at ${packagePath} must contain a non-empty string version.`);
  }

  const versionSource = `// Copyright (C) 2026 Tencent. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by scripts/sync-version.cjs from package.json. Do not edit.
export const VERSION = ${JSON.stringify(version)};
export const VERSION_TAG = \`v\${VERSION}\`;
`;
  if (readFileSync(versionPath, "utf8") !== versionSource) {
    writeFileSync(versionPath, versionSource, "utf8");
  }

  if (require("node:fs").existsSync(lockPath)) {
    const lockJson = parseJson(lockPath);
    let changed = false;
    if (lockJson.version !== version) {
      lockJson.version = version;
      changed = true;
    }
    if (lockJson.packages && lockJson.packages[""] && lockJson.packages[""].version !== version) {
      lockJson.packages[""].version = version;
      changed = true;
    }
    if (
      lockJson.packages
      && lockJson.packages["scripts/packaging/tsserver"]
      && lockJson.packages["scripts/packaging/tsserver"].version !== version
    ) {
      lockJson.packages["scripts/packaging/tsserver"].version = version;
      changed = true;
    }
    if (lockJson.packages?.[""]?.hasInstallScript === true) {
      delete lockJson.packages[""].hasInstallScript;
      changed = true;
    }
    if (changed) writeJson(lockPath, lockJson);
  }

  const tsserverPackage = parseJson(tsserverPackagePath);
  if (tsserverPackage.version !== version) {
    tsserverPackage.version = version;
    writeJson(tsserverPackagePath, tsserverPackage);
  }

  for (const readmePath of readmePaths) {
    syncReadme(readmePath, version);
  }
}

main();
